mybatis:
  typeAliasesPackage: com.zz.mybaits.entity
  mapperLocations: classpath:mapper/*.xml

server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/school?characterEncoding=utf8
    username: root
    password: Zheng1234
